#!/bin/bash
bar="\033[0;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"              
bar2="\033[0;31m=============================================\033[0m"
bar3="\033[0;31m---------------------------------------------\033[0m"
bar4="\033[0;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
bar5="\033[0;31m==================================================\033[0m"

#1-psi 443
installpsi443() {
	cd /root && mkdir psi && cd /root/psi && wget https://raw.githubusercontent.com/Psiphon-Labs/psiphon-tunnel-core-binaries/master/psiphond/psiphond && chmod 777 psiphond && ./psiphond --ipaddress 0.0.0.0 --protocol FRONTED-MEEK-OSSH:80 generate && screen -dmS PSI ./psiphond run && cat /root/psi/server-entry.dat;echo ''
	echo $bar
    echo "PSI EN PUERTO 443 INSTALADO"
	echo $bar
    
    

}

#2-psi 80
installpsi80() {
	cd /root && mkdir psi && cd /root/psi && wget https://raw.githubusercontent.com/Psiphon-Labs/psiphon-tunnel-core-binaries/master/psiphond/psiphond && chmod 777 psiphond && ./psiphond --ipaddress 0.0.0.0 --protocol FRONTED-MEEK-OSSH:443 generate && screen -dmS PSI ./psiphond run && cat /root/psi/server-entry.dat;echo ''
	echo $bar
    echo "PSI EN PUERTO 80 INSTALADO"
	echo $bar
    
    

}

#3-iniciar psi
runpsi() {
	cd /root/psi && screen -dmS PSI ./psiphond run
	echo $bar
    echo  "PSI INICIADO CON EXITO"
	echo $bar
   
    

}

#4-obtener codigo de tarjet
codetarjet() {
	cd /root/psi&&cat /root/psi/server-entry.dat;echo ''
	echo $bar
    echo "CODIGO TARJET OBTENIDO"
	echo $bar
    
    

}

#5-ver puertos activos
activeports() {
	netstat -tnpl
	echo $bar
    echo "PUERTOS VISUALIZADOS"
	echo $bar
    
    

}

#6-probar velocidad del vps
testspeed() {
	speedtest
	echo $bar
    echo "PRUEBA DE VELOCIDAD EJECUTADA"
	echo $bar
    
    

}

#7-refrescar memoria ram
cleanram() {
	sync & sysctl -w vm.drop_caches=3
	echo $bar
    echo "MEMORIA RAM LIMPIADA"
	echo $bar
    
    

}

#8-desinstalar psiphon
unisnstallpsi() {
	rm -rf /root/psi
	echo $bar
    echo "PSI DESINSTALADO"
	echo $bar
    echo -ne "Enter Para Continuar" && read enter
    

}

#9-ver usuarios conectados
#viewusers() {
	#cd /root/psi&&cat /root/psi/server-entry.dat;echo ''
	#echo $bar
    #echo -ama "$(fun_trans "Intalado con Exito")!"
	#echo $bar
    #echo -ne "Enter Para Continuar" && read enter
    #

#}

#PANEL PSIPPHON
clear
panelpsiphon (){
echo -e "\033[0;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[3;32m          >>>>   MENU PSIPHON V1   <<<<          \E[0m"
echo -e "\033[0;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALAR PSIPHON CON PUERTO 443"
echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALAR PSIPHON CON PUERTO 80"
echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mACTIVAR PSIPHON"
echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mOBTENER CODIGO TARJET"
echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mVER PUERTOS ACTIVOS"
echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mPROBAR VELOCIDAD DEL VPS"
echo -e "\033[1;31m[\033[1;36m7\033[1;31m] \033[1;37m• \033[1;33mREFRESCAR MEMORIA RAM"
echo -e "\033[1;31m[\033[1;36m8\033[1;31m] \033[1;37m• \033[1;33mDESINSTALAR PSIPHON"
echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \e[97m\033[1;41mVOLVER"
echo -e "\033[0;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -ne "\033[1;32mIngrese una opcion: \033[1;33m\033[1;31m?\033[1;37m "

read option
case $option in 

      1) 
         clear
         installpsi443
         echo -ne "Enter Para Continuar" && read enter
         clear
         panelpsiphon ;;
      2)  
         clear
         installpsi80
         echo -ne "Enter Para Continuar" && read enter
         clear
         panelpsiphon ;;
      3)  
         clear
         runpsi
         echo -ne "Enter Para Continuar" && read enter
         clear
         panelpsiphon ;;
      4) 
         clear
         codetarjet
         echo -ne "Enter Para Continuar" && read enter
         clear
         panelpsiphon ;;
      5)  
         clear
         activeports
         echo -ne "Enter Para Continuar" && read enter
         clear
         panelpsiphon ;;
      6)  
         clear
         testspeed
         echo -ne "Enter Para Continuar" && read enter
         clear
         panelpsiphon ;;
      7) 
         clear
         cleanram
         echo -ne "Enter Para Continuar" && read enter
         clear
         panelpsiphon ;;
      8)  
         clear
         unisnstallpsi
         echo -ne "Enter Para Continuar" && read enter
         clear
         panelpsiphon ;;
      0) 
        clear 
        bash <(curl -sL https://raw.githubusercontent.com/jorgemodxd/HERRAMIENTAS2/main/MENU%20DE%20PROTOCOLOS%20V2/MENUDEPROTOCOLOSv2) ;;
      *)
      echo -e "\n\033[1;31mOPCION INVALIDA !\033[0m"
      sleep 2
esac
}
panelpsiphon
